version: "3"

services:

  web:
    build: .
    ports:
      - "7002:5000"
    environment:
      PORT: "5000"
      MYSQL_HOST: mysql
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: q1w2e3r4
      SENTRY_DSN: ""
    volumes:
      - ./webapp:/opt/webapp
    depends_on:
      - mysql
    networks:
      - all

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "2002:3306"
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: q1w2e3r4
    networks:
      - all

networks: 
  all:
